services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: earthquake-monitor:prod
    ports:
      - "8000:8000"
    env_file:
      - ../.env.prod
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=earthquake_monitor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
