services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: earthquake-monitor:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/earthquake_monitor_dev
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    depends_on:
      - db
    volumes:
      - ../src:/app/src  # Mount source for hot reload
      - ../tests:/app/tests  # Mount tests for development and testing
    command: ["./startup.sh"]

  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=earthquake_monitor_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data


volumes:
  postgres_data_dev:
