global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Data Ingestion Service
  - job_name: 'data-ingestion-service'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Kafka metrics (if JMX exporter is configured)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  # Future services placeholder
  - job_name: 'disaster-core-service'
    static_configs:
      - targets: []
    scrape_interval: 15s

  - job_name: 'alert-processing-service'
    static_configs:
      - targets: []
    scrape_interval: 15s
