name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: earthquake_monitor_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r earthquake-monitor/requirements.txt

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for postgres..."
          sleep 2
        done

    - name: Run Alembic migrations
      run: |
        cd earthquake-monitor
        echo "Running Alembic migrations..."
        alembic -c alembic_test.ini upgrade head
        echo "Verifying tables exist..."
        psql -h localhost -U postgres -d earthquake_monitor_test -c "\dt"
      env:
        DATABASE_URL: postgresql://postgres:password@localhost:5432/earthquake_monitor_test
        PGPASSWORD: password

    - name: Run unit tests
      run: |
        cd earthquake-monitor
        python -m pytest tests/unit/ -v --cov=src --cov-report=xml
      env:
        REPOSITORY_TYPE: mock

    - name: Run integration tests (mock)
      run: |
        cd earthquake-monitor
        python -m pytest tests/integration/ -v --cov=src --cov-append --cov-report=xml -k "not test_earthquake_api_with_db"
      env:
        REPOSITORY_TYPE: mock

    - name: Run database integration tests
      run: |
        cd earthquake-monitor
        python -m pytest tests/integration/test_earthquake_api_with_db.py -v --cov=src --cov-append --cov-report=xml
      env:
        DATABASE_URL: postgresql://postgres:password@localhost:5432/earthquake_monitor_test
        REPOSITORY_TYPE: postgresql

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./earthquake-monitor/coverage.xml
        fail_ci_if_error: false
